version: 1
formatters:
  standard:
#    format: '%(asctime)s - %(levelname)s - %(name)s - %(message)s'
    format: '%(message)s'
  verbose:
    format: '%(asctime)s - %(levelname)s <PID %(process)d:%(processName)s> %(module)s.%(funcName)s(): %(message)s'
handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: standard
    stream: ext://sys.stdout
#    propagate: yes
  valeo_log:
    class: logging.FileHandler
    filename: C:/EXED/Training/___VALEO/log/valeo.log
    mode: w
    level: DEBUG
    formatter: standard
#    propagate: yes

#  errors:
#    class: logging.FileHandler
#    filename: mplog-errors.log
#    mode: w
#    level: ERROR
#    formatter: detailed
#loggers:
#  simpleExample:
#    level: DEBUG
#    handlers: [console]
#    propagate: no
root:
  level: DEBUG
  handlers: [console, valeo_log]
  formatter: standard